# Site settings
title: Bavarian's Blog
description: Bavarian's professional resume
favicon: /assets/img/avatar.JPG
baseurl: https://etem.github.io/iCard-Resume
url: https://etem.github.io/iCard-Resume
rss_url: /pages/atom.xml
future : true
encoding : UTF-8

# Build settings
markdown: kramdown

# Author settings
author:
  name: Etem Hyusnev
  title: Network Support Specialist
  address: Varna, Bulgaria
  email: mr.cyberpower@gmail.com
  link: https://etem.github.io
  #weibo:
  github: etem
  linkedin: bavarian
  twitter: hyusnev
  gavatar: /assets/img/avatar3.png
  workHistory:
    - work1:
      company: Rutil Ltd
      location: Varna, Bulgaria
      title: Network Support Specialist
      started: 2014
      duration: (01.08.2014 - Present)
      description: Configuring MikroTiK wireless devices.Network support and administration.Troubleshooting and resolving network issues.
#    - work2:
#      company: Hewlett Packard Enterprise (HPE)
#      location: Sofia, Bulgaria
#      title: Network Implementation Engineer
#      started: August 2016
#      duration: (2016 - Present)
#      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
#    - work3:
#      company: Citigroup Services and Technology (China) Limited
#      location: Shanghai, China
#      title: Java Developer
#      started: 2009
#      duration: (2009 - 2012)
#      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: Technical University - Varna
      degree: Bachelor
      major: Computer Systems and Technology
      started: 2016
      duration: (2016 - Present)
#      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - education2:
      organization: Cisco Networking Academy - Technical University - Varna
      degree: Student
      major: Networking
      started: 2014
      duration: (2014 - 2015)
      description: Successfully finished CCNA Routing and Switching course and achieved CCNA Routing and Switching certificate with License No 420434170463DSDG.

  languages:
    - language1:
      name: Bulgarian
      proficiency: Native
    - language2:
      name: Turkish
      proficiency: Native
    - language3:
      name: English
      proficiency: Professional
    - language4:
      name: German
      proficiency: Limited
  programmingSkills:
    - skill1:
      name: Cisco Technologies
      percentage: 80%
    - skill2:
      name: System Administration
      percentage: 80%
    - skill3:
      name: MikroTiK
      percentage: 80%
    - skill4:
      name: Wireless Networking
      percentage: 70%
    - skill5:
      name: Python Programming
      percentage: 50%
    - skill6:
      name: Passion
      percentage: 100%
#   programmingSkills:
#     - skill1:
#       name: HTML
#       percentage: 100%
#     - skill2:
#       name: Bootstrap
#      percentage: 90%
#    - skill3:
#      name: JavaScript
#      percentage: 80%
#    - skill4:
#      name: AngularJS
#      percentage: 80%
#    - skill5:
#      name: Java/Java EE
#      percentage: 90%
